name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install crates
      run: |
        cargo install --debug cargo-quickinstall
        cargo quickinstall cargo-sort cargo-audit cargo-udeps
    - name: Lint
      run: |
        cargo fmt -- --check
        cargo sort --check
        cargo audit -D warnings
        cargo check
        cargo build
        cargo clippy -- -Dwarnings -D clippy::pedantic -D clippy::dbg-macro -A clippy::missing-errors-doc -A clippy::missing-panics-doc -A clippy::doc-markdown -A clippy::cast-precision-loss -A clippy::cast-possible-truncation -A clippy::module-name-repetitions
        cargo test
        RUSTC_BOOTSTRAP=1 cargo udeps
